name: Build Release
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    name: 构建发行版
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: 配置 Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: 安装依赖
        run: |
          python.exe -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt
          pip list
          echo ========================================
          $upx_url = (Invoke-WebRequest -Uri https://api.github.com/repos/upx/upx/releases/latest).Content | ConvertFrom-Json | Select-Object -ExpandProperty assets | Where-Object { $_.name -like "*win64.zip" } | Select-Object -ExpandProperty browser_download_url
          Write-Host "[INFO] Latest UPX download URL: $upx_url"
          Invoke-WebRequest -Uri $upx_url -OutFile "upx-latest.zip"
          7z x "upx-latest.zip" -o"."

      - name: 整理文件
        run: |
          robocopy ".\程序脚本" "version\Code\zh-CN" /e
          robocopy ".\other-languages\en_US" "version\Code\en-US" /e
          robocopy . "version\Code\zh-CN\" LICENSE
          robocopy . "version\Code\en-US\" LICENSE
        continue-on-error: true

      - name: 压缩发行版
        run: |
          7z a .\version\Release\zh-CN\GitHub-Labels-Manager-v1.7.zip .\version\Code\zh-CN
          7z a .\version\Release\en-US\GitHub-Labels-Manager-v1.7-EN.zip .\version\Code\en-US
          7z a .\version\Release\zh-CN\GitHub-Labels-Manager-v1.7.7z .\version\Code\zh-CN
          7z a .\version\Release\en-US\GitHub-Labels-Manager-v1.7-EN.7z .\version\Code\en-US

      - name: 打包发行版
        run: |
          pyinstaller --onefile -i ico.ico --distpath=.\version\Code\zh-CN --name=glm.exe .\version\Code\zh-CN\glm.py --hiddenimport win32timezone
          echo ======================================
          pyinstaller --onefile -i ico.ico --distpath=.\version\Code\en-US --name=glm.exe .\version\Code\en-US\glm.py --hiddenimport win32timezone
          echo ======================================
          del .\version\Code\zh-CN\glm.py
          del .\version\Code\en-US\glm.py

      - name: 配置 Inno 中文翻译
        run: |
          curl -o "C:\Program Files (x86)\Inno Setup 6\Languages\ChineseSimplified.isl" "https://raw.githubusercontent.com/jrsoftware/issrc/main/Files/Languages/Unofficial/ChineseSimplified.isl"

      - name: 验证文件
        run: |
          tree /f

      - name: 打包安装程序
        run: |
          iscc pack.iss
          echo =======================
          iscc packEN.iss

      - name: 上传构建文件
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            .\version\Release\zh-CN\*
            .\version\Release\en-US\*
