name: Build Release
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    name: 构建发行版
    runs-on: windows-latest

    steps:
      - name: 签出代码
        uses: actions/checkout@v4

      - name: 配置 Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: 安装依赖
        run: |
          python.exe -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt
          pip list
          echo ========================================
          $upx_url = (Invoke-WebRequest -Uri https://api.github.com/repos/upx/upx/releases/latest).Content | ConvertFrom-Json | Select-Object -ExpandProperty assets | Where-Object { $_.name -like "*win64.zip" } | Select-Object -ExpandProperty browser_download_url
          Write-Host "[INFO] Latest UPX download URL: $upx_url"
          Invoke-WebRequest -Uri $upx_url -OutFile "upx-latest.zip"
          7z x "upx-latest.zip" -o"."

      - name: 整理文件
        run: |
          robocopy ".\程序脚本" "version\Code\en_US" /e
          robocopy ".\other-languages\en_US" "version\Code\en-US" /e
          robocopy . "version\Code\en_US\" LICENSE
          robocopy . "version\Code\en-US\" LICENSE
        continue-on-error: true

      # ============ Compile ============

      - name: 压缩发行版
        run: |
          7z a .\version\Release\en_US\GitHub-Labels-Manager-v1.9.zip .\version\Code\en_US
          7z a .\version\Release\en-US\GitHub-Labels-Manager-v1.9-EN.zip .\version\Code\en-US
          7z a .\version\Release\en_US\GitHub-Labels-Manager-v1.9.7z .\version\Code\en_US
          7z a .\version\Release\en-US\GitHub-Labels-Manager-v1.9-EN.7z .\version\Code\en-US

      - name: 打包发行版
        run: |
          pyinstaller --onefile -i ico.ico --distpath=.\version\Code\en_US --name=glm.exe .\version\Code\en_US\glm.py --hiddenimport win32timezone
          echo ======================================
          pyinstaller --onefile -i ico.ico --distpath=.\version\Code\en-US --name=glm.exe .\version\Code\en-US\glm.py --hiddenimport win32timezone
          echo ======================================
          del .\version\Code\en_US\glm.py
          del .\version\Code\en-US\glm.py

      - name: 配置 Inno 中文翻译
        run: |
          curl -o "C:\Program Files (x86)\Inno Setup 6\Languages\ChineseSimplified.isl" "https://raw.githubusercontent.com/jrsoftware/issrc/main/Files/Languages/Unofficial/ChineseSimplified.isl"

      - name: 验证文件
        run: |
          tree /f /a

      - name: 打包安装程序
        run: |
          iscc pack.iss
          echo =======================
          iscc packEN.iss

      # ============ TEST ============

      - name: 测试源码
        run: |
          echo ============ EN ============
          echo xxxxxxxxxxxx HELP xxxxxxxxxxxx
          python "other-languages\en_US\glm.py" --help
          python "other-languages\en_US\glm.py" get --help
          python "other-languages\en_US\glm.py" set --help
          python "other-languages\en_US\glm.py" copy --help
          python "other-languages\en_US\glm.py" config --help
          python "other-languages\en_US\glm.py" clear --help

          echo xxxxxxxxxxxx USE xxxxxxxxxxxx
          python "other-languages\en_US\glm.py" get https://github.com/DuckDuckStudio/Fufu_Tools --save "labels.json"
          Get-Content .\labels.json -Encoding UTF8
          del .\labels.json

          python "other-languages\en_US\glm.py" config --version
          python "other-languages\en_US\glm.py" config --show

      - name: 测试打包
        run: |
          echo ============ EN ============
          echo xxxxxxxxxxxx HELP xxxxxxxxxxxx
          & "version\Code\en_US\glm.exe" --help
          & "version\Code\en_US\glm.exe" get --help
          & "version\Code\en_US\glm.exe" set --help
          & "version\Code\en_US\glm.exe" copy --help
          & "version\Code\en_US\glm.exe" config --help
          & "version\Code\en_US\glm.exe" clear --help
      
          echo xxxxxxxxxxxx USE xxxxxxxxxxxx
          & "version\Code\en_US\glm.exe" get https://github.com/DuckDuckStudio/Fufu_Tools --save "labels.json"
          Get-Content .\labels.json -Encoding UTF8
          del .\labels.json
      
          & "version\Code\en_US\glm.exe" config --version
          & "version\Code\en_US\glm.exe" config --show

      - name: 测试安装程序-INSTALL
        run: |
          & "version\Release\en_US\GitHub_Labels_Manager_Setup_v1.9-EN.exe" /verysilent /suppressmsgboxes
      
      - name: 测试安装程序-RUN
        run: |
          echo ============ ZH ============
          echo xxxxxxxxxxxx HELP xxxxxxxxxxxx
          glm --help
          glm get --help
          glm set --help
          glm copy --help
          glm config --help
          glm clear --help
  
          echo xxxxxxxxxxxx USE xxxxxxxxxxxx
          glm get https://github.com/DuckDuckStudio/Fufu_Tools --save "labels.json"
          Get-Content .\labels.json -Encoding UTF8
          del .\labels.json
  
          glm config --version
          glm config --show

      # ============ Upload ============

      - name: 上传构建文件
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            .\version\Release\en_US\*
            .\version\Release\en-US\*